In [ ]:
import numpy as np
arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.sum(arr,axis=0)

array([ 9, 12, 15])

In [ ]:
import numpy as np

# Extracting numeric data as NumPy arrays for future analysis
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])
costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])
rate = np.array([4.1, 3.8, 4.0, 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])

print("Votes (Array):", votes)
print("Costs (Array):", costs)
print("Ratings (Array):", rate)

Votes (Array): [ 775  787  918   88  166  286 2556  324  504  402]
Costs (Array): ["'800.0'" "'800.0'" "'800.0'" "'300.0'" "'600.0'" "'600.0'" "'600.0'"
 "'700.0'" "'550.0'" "'500.0'"]
Ratings (Array): [4.1 3.8 4.  2.6 1.1 3.5 4.7 2.5 2.8 3.4]


1. Sorting a 1D Array 🗂️
We’ll sort a simple 1D array using:

np.sort(): Returns a sorted copy.<Br>
np.argsort(): Returns indices that would sort the array.

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
sorted_votes = np.sort(votes)       # Sort the votes
print("Sorted Votes:", sorted_votes)

Sorted Votes: [  88  166  286  324  402  504  775  787  918 2556]


In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
votes[[0,2,3]]

array([775, 918,  88])

In [ ]:
sorted_indices = np.argsort(votes)  # Indices that would sort the votes
print("Indices for Sorting:", sorted_indices)

Indices for Sorting: [3 4 5 7 9 8 0 1 2 6]


In [ ]:
votes[np.argsort(votes)]

array([  88,  166,  286,  324,  402,  504,  775,  787,  918, 2556])

In [ ]:
votes[np.argsort(votes)][::-1] #doubts

array([2556,  918,  787,  775,  504,  402,  324,  286,  166,   88])

# 2D array

In [ ]:
# Example 2D array
array_2d = np.array([[34, 11, 8],
                     [7, 45, 18],
                     [9, 23, 20]])

In [ ]:
np.sort(array_2d, axis=0)

array([[ 7, 11,  8],
       [ 9, 23, 18],
       [34, 45, 20]])

In [ ]:
np.sort(array_2d, axis=1)

array([[ 8, 11, 34],
       [ 7, 18, 45],
       [ 9, 20, 23]])

# Matrix Multiplication in NumPy

In [ ]:
np.set_printoptions(suppress=False, precision=1)


In [ ]:
# Your numeric_data array
numeric_data = np.array([
    [4.1, 775.0, 800.0],
    [3.8, 787.0, 800.0],
    [4.0, 918.0, 800.0],
    [2.6, 88.0, 300.0],
    [1.1, 166.0, 600.0],
    [3.5, 286.0, 600.0],
    [4.7, 2556.0, 600.0],
    [2.5, 324.0, 700.0],
    [2.8, 504.0, 550.0],
    [3.4, 402.0, 500.0]
])
numeric_data

array([[4.1e+00, 7.8e+02, 8.0e+02],
       [3.8e+00, 7.9e+02, 8.0e+02],
       [4.0e+00, 9.2e+02, 8.0e+02],
       [2.6e+00, 8.8e+01, 3.0e+02],
       [1.1e+00, 1.7e+02, 6.0e+02],
       [3.5e+00, 2.9e+02, 6.0e+02],
       [4.7e+00, 2.6e+03, 6.0e+02],
       [2.5e+00, 3.2e+02, 7.0e+02],
       [2.8e+00, 5.0e+02, 5.5e+02],
       [3.4e+00, 4.0e+02, 5.0e+02]])

In [ ]:
np.set_printoptions(suppress=True, precision=1)


In [ ]:
numeric_data

array([[   4.1,  775. ,  800. ],
       [   3.8,  787. ,  800. ],
       [   4. ,  918. ,  800. ],
       [   2.6,   88. ,  300. ],
       [   1.1,  166. ,  600. ],
       [   3.5,  286. ,  600. ],
       [   4.7, 2556. ,  600. ],
       [   2.5,  324. ,  700. ],
       [   2.8,  504. ,  550. ],
       [   3.4,  402. ,  500. ]])

In [ ]:
votes = numeric_data[:, 1]  # Extract 'votes'
votes

array([ 775.,  787.,  918.,   88.,  166.,  286., 2556.,  324.,  504.,
        402.])

In [ ]:
ratings = numeric_data[:, 0]  # Extract 'rate' column
ratings

array([4.1, 3.8, 4. , 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])

In [ ]:
weighted_scores = votes * ratings
weighted_scores

array([ 3177.5,  2990.6,  3672. ,   228.8,   182.6,  1001. , 12013.2,
         810. ,  1411.2,  1366.8])

Takeaway:

Array * Number  →  WORKS
Array * Array (same shape)  →  WORKS
Array * Array (different shape)  →  DOES NOT WORK

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr*arr #eleemnt wise mult

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

# . Matrix Multiplication 📐
 -- np.dot()
 -- np.matmul()
 -- @ operator.

In [ ]:
numeric_data

array([[   4.1,  775. ,  800. ],
       [   3.8,  787. ,  800. ],
       [   4. ,  918. ,  800. ],
       [   2.6,   88. ,  300. ],
       [   1.1,  166. ,  600. ],
       [   3.5,  286. ,  600. ],
       [   4.7, 2556. ,  600. ],
       [   2.5,  324. ,  700. ],
       [   2.8,  504. ,  550. ],
       [   3.4,  402. ,  500. ]])

In [ ]:
numeric_data.shape

(10, 3)

In [ ]:
# Create a random transformation matrix
transformation_matrix = np.array([[1.2, 0.8, 0.5],
                                   [0.5, 1.5, 1.0],
                                   [0.7, 0.6, 1.8]])
transformation_matrix

array([[1.2, 0.8, 0.5],
       [0.5, 1.5, 1. ],
       [0.7, 0.6, 1.8]])

In [ ]:
transformation_matrix.shape

(3, 3)

In [ ]:


# Matrix multiplication using np.dot()
transformed_data_dot = np.dot(numeric_data, transformation_matrix)
transformed_data_dot

array([[ 952.4, 1645.8, 2217.1],
       [ 958.1, 1663.5, 2228.9],
       [1023.8, 1860.2, 2360. ],
       [ 257.1,  314.1,  629.3],
       [ 504.3,  609.9, 1246.5],
       [ 567.2,  791.8, 1367.8],
       [1703.6, 4197.8, 3638.3],
       [ 655. ,  908. , 1585.2],
       [ 640.4, 1088.2, 1495.4],
       [ 555.1,  905.7, 1303.7]])

In [ ]:
# Matrix multiplication using @ operator
transformed_data_at = numeric_data @ transformation_matrix

# Matrix multiplication using np.matmul()
transformed_data_matmul = np.matmul(numeric_data, transformation_matrix)

In [ ]:
print("Transformed Data (np.dot):\n", transformed_data_dot[:5])
print("---"* 10)
print("Transformed Data (@ operator):\n", transformed_data_at[:5])
print("---"* 10)
print("Transformed Data (np.matmul):\n", transformed_data_matmul[:5])
print("---"* 10)

Transformed Data (np.dot):
 [[ 952.4 1645.8 2217.1]
 [ 958.1 1663.5 2228.9]
 [1023.8 1860.2 2360. ]
 [ 257.1  314.1  629.3]
 [ 504.3  609.9 1246.5]]
------------------------------
Transformed Data (@ operator):
 [[ 952.4 1645.8 2217.1]
 [ 958.1 1663.5 2228.9]
 [1023.8 1860.2 2360. ]
 [ 257.1  314.1  629.3]
 [ 504.3  609.9 1246.5]]
------------------------------
Transformed Data (np.matmul):
 [[ 952.4 1645.8 2217.1]
 [ 958.1 1663.5 2228.9]
 [1023.8 1860.2 2360. ]
 [ 257.1  314.1  629.3]
 [ 504.3  609.9 1246.5]]
------------------------------


In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a@5

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
np.matmul(a, 5)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
np.dot(a, 5)

array([ 5, 10, 15, 20])

# Vectorization in NumPy 🚀

In [ ]:
# Example: Apply a custom function to the 'rate' column
def categorize_rating(rating):
  if rating >=4.0:
    return "High"
  else:
    return "Low"

In [ ]:
categorize_rating(4.3)

'High'

In [ ]:
categorize_rating(3.3)

'Low'

In [ ]:
# Attempt to apply the function directly
categorized_ratings = categorize_rating(numeric_data[:, 0])  # 'rate' column
categorized_ratings

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# Vectorize the categorize_rating function
vectorized_categorize_rating = np.vectorize(categorize_rating)
vectorized_categorize_rating

In [ ]:
numeric_data[:, 0]

array([4.1, 3.8, 4. , 2.6, 1.1, 3.5, 4.7, 2.5, 2.8, 3.4])

In [ ]:
categorized_ratings = vectorized_categorize_rating(numeric_data[:, 0])
categorized_ratings

array(['High', 'Low', 'High', 'Low', 'Low', 'Low', 'High', 'Low', 'Low',
       'Low'], dtype='<U4')

Imagine we want to apply a 10% discount to restaurants with a rating of 4.0 or higher.
We’ll use np.vectorize() to vectorize the logic and apply it to the dataset.

In [ ]:
numeric_data

array([[   4.1,  775. ,  800. ],
       [   3.8,  787. ,  800. ],
       [   4. ,  918. ,  800. ],
       [   2.6,   88. ,  300. ],
       [   1.1,  166. ,  600. ],
       [   3.5,  286. ,  600. ],
       [   4.7, 2556. ,  600. ],
       [   2.5,  324. ,  700. ],
       [   2.8,  504. ,  550. ],
       [   3.4,  402. ,  500. ]])

In [ ]:
# Define a function to calculate discounted cost
def discount_cost(rate, cost):
    """Apply a 10% discount if the rating is 4.0 or higher."""
    if rate >= 4.0:
        return cost * 0.9 #100*0.9 - 90
    else:
        return cost

In [ ]:
# Vectorize the discount_cost function
vectorized_discount_cost = np.vectorize(discount_cost)

# Apply the vectorized function to 'rate' and 'approx_cost(for two people)'
discounted_costs = vectorized_discount_cost(numeric_data[:, 0], numeric_data[:, 2])

# Display a sample of the discounted costs
print("Discounted Costs (sample):", discounted_costs[:10])

Discounted Costs (sample): [720. 800. 720. 300. 600. 600. 540. 700. 550. 500.]


# Using np.tile()

In [ ]:
# Example: Explicit broadcasting with np.tile
array1 = np.array([[1, 2, 3]])
array2 = np.array([[10], [20], [30]])

In [ ]:
array1

array([[1, 2, 3]])

In [ ]:
np.tile(array1,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.tile(array1,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

# Splitting Arrays in NumPy ✂️

In [ ]:
# 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])
array_1d

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Split into 3 sections
np.split(array_1d, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
# Split into 3 sections
np.split(array_1d, 4)

ValueError: array split does not result in an equal division

In [ ]:
# 2D array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

# Split into 2 along axis=1 (columns)
split_2d = np.split(array_2d, 2, axis=1)

split_2d

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [ ]:
np.hsplit(array_2d, 2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [ ]:
array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
 np.vsplit(array_2d, 2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [ ]:
# 2D array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

# Split into 2 along axis=1 (columns)
split_2d = np.split(array_2d, [1,3], axis=1)

split_2d

[array([[1, 2, 3],
        [5, 6, 7]]),
 array([[4],
        [8]])]

In [ ]:
# Define arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
# Stack vertically
vstack_result = np.vstack([array1, array2])
vstack_result

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Define arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
# Stack vertically
vstack_result = np.hstack([array1, array2])
vstack_result

array([1, 2, 3, 4, 5, 6])