In [ ]:
!pip install pandas

In [ ]:
# Downloading and unziping the dataset
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip


--2025-05-19 17:22:22--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 108.157.172.10, 108.157.172.173, 108.157.172.176, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|108.157.172.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M   229MB/s    in 0.3s    

2025-05-19 17:22:23 (229 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv      
mv: 'zomato_dataset.csv' and './zomato_dataset.csv' are the same file


In [ ]:
import pandas as pd

In [ ]:
pd.read_csv("zomato_dataset.csv")

url  \
0      https://www.zomato.com/bangalore/jalsa-banasha...   
1      https://www.zomato.com/bangalore/spice-elephan...   
2      https://www.zomato.com/SanchurroBangalore?cont...   
3      https://www.zomato.com/bangalore/addhuri-udupi...   
4      https://www.zomato.com/bangalore/grand-village...   
...                                                  ...   
23188  https://www.zomato.com/bangalore/izakaya-gastr...   
23189  https://www.zomato.com/bangalore/m-bar-bengalu...   
23190  https://www.zomato.com/bangalore/keys-cafe-key...   
23191  https://www.zomato.com/bangalore/bhagini-2-whi...   
23192  https://www.zomato.com/bangalore/chime-sherato...   

                                                 address  \
0      942, 21st Main Road, 2nd Stage, Banashankari, ...   
1      2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...   
2      1112, Next to KIMS Medical College, 17th Cross...   
3      1st Floor, Annakuteera, 3rd Stage, Banashankar...   
4      10, 3rd Floor, Lakshmi Associates, Gandhi Baza...   
...                                                  ...   
23188  2nd Floor, Iona, Virginia Mall, Whitefield Mai...   
23189  Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...   
23190  Keys Hotel, 6, 1st Phase Industrial Area, Near...   
23191  139/C1, Next To GR Tech Park, Pattandur Agraha...   
23192  Sheraton Grand Bengaluru Whitefield Hotel & Co...   

                                                    name online_order  \
0                                                  Jalsa          Yes   
1                                         Spice Elephant          Yes   
2                                        San Churro Cafe          Yes   
3                                  Addhuri Udupi Bhojana           No   
4                                          Grand Village           No   
...                                                  ...          ...   
23188                                 Izakaya Gastro Pub          Yes   
23189        M Bar - Bengaluru Marriott Hotel Whitefield           No   
23190                             Keys Cafe - Keys Hotel           No   
23191                                            Bhagini           No   
23192  Chime - Sheraton Grand Bengaluru Whitefield Ho...           No   

      book_table    rate  votes                             phone  \
0            Yes   4.1/5    775    080 42297555\r\n+91 9743772233   
1             No   4.1/5    787                      080 41714161   
2             No   3.8/5    918                    +91 9663487993   
3             No   3.7/5     88                    +91 9620009302   
4             No   3.8/5    166  +91 8026612447\r\n+91 9901210005   
...          ...     ...    ...                               ...   
23188        Yes  3.8 /5    128    +91 7625087121\n+91 8050587483   
23189         No  3.9 /5     77                      080 49435000   
23190         No  2.8 /5    161      080 39451000\n+91 8884038484   
23191         No  2.5 /5     81                      080 65951222   
23192        Yes  4.3 /5    236                      080 49652769   

                         location            rest_type  \
0                    Banashankari        Casual Dining   
1                    Banashankari        Casual Dining   
2                    Banashankari  Cafe, Casual Dining   
3                    Banashankari          Quick Bites   
4                    Basavanagudi        Casual Dining   
...                           ...                  ...   
23188                  Whitefield   Bar, Casual Dining   
23189                  Whitefield     Fine Dining, Bar   
23190                  Whitefield   Casual Dining, Bar   
23191                  Whitefield   Casual Dining, Bar   
23192  ITPL Main Road, Whitefield                  Bar   

                                              dish_liked  \
0      Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1      Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
2      Churros, Cannelloni, 

In [ ]:
df = pd.read_csv("zomato_dataset.csv")

In [ ]:
df.head()# first 5 rows

url  \
0  https://www.zomato.com/bangalore/jalsa-banasha...   
1  https://www.zomato.com/bangalore/spice-elephan...   
2  https://www.zomato.com/SanchurroBangalore?cont...   
3  https://www.zomato.com/bangalore/addhuri-udupi...   
4  https://www.zomato.com/bangalore/grand-village...   

                                             address                   name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...                  Jalsa   
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...         Spice Elephant   
2  1112, Next to KIMS Medical College, 17th Cross...        San Churro Cafe   
3  1st Floor, Annakuteera, 3rd Stage, Banashankar...  Addhuri Udupi Bhojana   
4  10, 3rd Floor, Lakshmi Associates, Gandhi Baza...          Grand Village   

  online_order book_table   rate  votes                             phone  \
0          Yes        Yes  4.1/5    775    080 42297555\r\n+91 9743772233   
1          Yes         No  4.1/5    787                      080 41714161   
2          Yes         No  3.8/5    918                    +91 9663487993   
3           No         No  3.7/5     88                    +91 9620009302   
4           No         No  3.8/5    166  +91 8026612447\r\n+91 9901210005   

       location            rest_type  \
0  Banashankari        Casual Dining   
1  Banashankari        Casual Dining   
2  Banashankari  Cafe, Casual Dining   
3  Banashankari          Quick Bites   
4  Basavanagudi        Casual Dining   

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
2  Churros, Cannelloni, Minestrone Soup, Hot Choc...   
3                                        Masala Dosa   
4                                Panipuri, Gol Gappe   

                         cuisines approx_cost(for two people)  \
0  North Indian, Mughlai, Chinese                     '800.0'   
1     Chinese, North Indian, Thai                     '800.0'   
2          Cafe, Mexican, Italian                     '800.0'   
3      South Indian, North Indian                     '300.0'   
4        North Indian, Rajasthani                     '600.0'   

                                        reviews_list menu_item  \
0  [('Rated 4.0', 'RATED\n  A beautiful place to ...        []   
1  [('Rated 4.0', 'RATED\n  Had been here for din...        []   
2  [('Rated 3.0', "RATED\n  Ambience is not that ...        []   
3  [('Rated 4.0', "RATED\n  Great food and proper...        []   
4  [('Rated 4.0', 'RATED\n  Very good restaurant ...        []   

  listed_in(type) listed_in(city)  
0          Buffet    Banashankari  
1          Buffet    Banashankari  
2          Buffet    Banashankari  
3          Buffet    Banashankari  
4          Buffet    Banashankari

In [ ]:
df.tail()# last 5 rows

url  \
23188  https://www.zomato.com/bangalore/izakaya-gastr...   
23189  https://www.zomato.com/bangalore/m-bar-bengalu...   
23190  https://www.zomato.com/bangalore/keys-cafe-key...   
23191  https://www.zomato.com/bangalore/bhagini-2-whi...   
23192  https://www.zomato.com/bangalore/chime-sherato...   

                                                 address  \
23188  2nd Floor, Iona, Virginia Mall, Whitefield Mai...   
23189  Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...   
23190  Keys Hotel, 6, 1st Phase Industrial Area, Near...   
23191  139/C1, Next To GR Tech Park, Pattandur Agraha...   
23192  Sheraton Grand Bengaluru Whitefield Hotel & Co...   

                                                    name online_order  \
23188                                 Izakaya Gastro Pub          Yes   
23189        M Bar - Bengaluru Marriott Hotel Whitefield           No   
23190                             Keys Cafe - Keys Hotel           No   
23191                                            Bhagini           No   
23192  Chime - Sheraton Grand Bengaluru Whitefield Ho...           No   

      book_table    rate  votes                           phone  \
23188        Yes  3.8 /5    128  +91 7625087121\n+91 8050587483   
23189         No  3.9 /5     77                    080 49435000   
23190         No  2.8 /5    161    080 39451000\n+91 8884038484   
23191         No  2.5 /5     81                    080 65951222   
23192        Yes  4.3 /5    236                    080 49652769   

                         location           rest_type  \
23188                  Whitefield  Bar, Casual Dining   
23189                  Whitefield    Fine Dining, Bar   
23190                  Whitefield  Casual Dining, Bar   
23191                  Whitefield  Casual Dining, Bar   
23192  ITPL Main Road, Whitefield                 Bar   

                                              dish_liked  \
23188  Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...   
23189                                   Rooftop Ambience   
23190  Salads, Coffee, Breakfast Buffet, Halwa, Chick...   
23191                               Biryani, Andhra Meal   
23192                       Cocktails, Pizza, Buttermilk   

                                          cuisines  \
23188     North Indian, Continental, Mediterranean   
23189                                  Finger Food   
23190           Chinese, Continental, North Indian   
23191  Andhra, South Indian, Chinese, North Indian   
23192                                  Finger Food   

      approx_cost(for two people)  \
23188                    '1200.0'   
23189                    '2000.0'   
23190                    '1200.0'   
23191                     '800.0'   
23192                    '2500.0'   

                                            reviews_list menu_item  \
23188  [('Rated 3.0', "RATED\n  Nice place to hangout...        []   
23189  [('Rated 4.0', 'RATED\n  Went there post dinne...        []   
23190  [('Rated 3.0', 'RATED\n  Place is good not tha...        []   
23191  [('Rated 4.0', 'RATED\n  A fine place to chill...        []   
23192  [('Rated 4.0', 'RATED\n  Nice and friendly pla...        []   

      listed_in(type) listed_in(city)  
23188   Pubs and bars      Whitefield  
23189   Pubs and bars      Whitefield  
23190   Pubs and bars      Whitefield  
23191   Pubs and bars      Whitefield  
23192   Pubs and bars      Whitefield

In [ ]:
df.shape()

TypeError: 'tuple' object is not callable

In [ ]:
df.shape

(23193, 17)

In [ ]:
df.head(2)# first 2 rows

url  \
0  https://www.zomato.com/bangalore/jalsa-banasha...   
1  https://www.zomato.com/bangalore/spice-elephan...   

                                             address            name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...           Jalsa   
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...  Spice Elephant   

  online_order book_table   rate  votes                           phone  \
0          Yes        Yes  4.1/5    775  080 42297555\r\n+91 9743772233   
1          Yes         No  4.1/5    787                    080 41714161   

       location      rest_type  \
0  Banashankari  Casual Dining   
1  Banashankari  Casual Dining   

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   

                         cuisines approx_cost(for two people)  \
0  North Indian, Mughlai, Chinese                     '800.0'   
1     Chinese, North Indian, Thai                     '800.0'   

                                        reviews_list menu_item  \
0  [('Rated 4.0', 'RATED\n  A beautiful place to ...        []   
1  [('Rated 4.0', 'RATED\n  Had been here for din...        []   

  listed_in(type) listed_in(city)  
0          Buffet    Banashankari  
1          Buffet    Banashankari

In [ ]:
# Use .head() to preview the top 5 rows of the dataset.
# Use .head(n) to preview the top n rows of the dataset.
# Use .tail(n) to preview the bottom n rows of the dataset.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64 
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23

In [ ]:
df.head()

url  \
0  https://www.zomato.com/bangalore/jalsa-banasha...   
1  https://www.zomato.com/bangalore/spice-elephan...   
2  https://www.zomato.com/SanchurroBangalore?cont...   
3  https://www.zomato.com/bangalore/addhuri-udupi...   
4  https://www.zomato.com/bangalore/grand-village...   

                                             address                   name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...                  Jalsa   
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...         Spice Elephant   
2  1112, Next to KIMS Medical College, 17th Cross...        San Churro Cafe   
3  1st Floor, Annakuteera, 3rd Stage, Banashankar...  Addhuri Udupi Bhojana   
4  10, 3rd Floor, Lakshmi Associates, Gandhi Baza...          Grand Village   

  online_order book_table   rate  votes                             phone  \
0          Yes        Yes  4.1/5    775    080 42297555\r\n+91 9743772233   
1          Yes         No  4.1/5    787                      080 41714161   
2          Yes         No  3.8/5    918                    +91 9663487993   
3           No         No  3.7/5     88                    +91 9620009302   
4           No         No  3.8/5    166  +91 8026612447\r\n+91 9901210005   

       location            rest_type  \
0  Banashankari        Casual Dining   
1  Banashankari        Casual Dining   
2  Banashankari  Cafe, Casual Dining   
3  Banashankari          Quick Bites   
4  Basavanagudi        Casual Dining   

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
2  Churros, Cannelloni, Minestrone Soup, Hot Choc...   
3                                        Masala Dosa   
4                                Panipuri, Gol Gappe   

                         cuisines approx_cost(for two people)  \
0  North Indian, Mughlai, Chinese                     '800.0'   
1     Chinese, North Indian, Thai                     '800.0'   
2          Cafe, Mexican, Italian                     '800.0'   
3      South Indian, North Indian                     '300.0'   
4        North Indian, Rajasthani                     '600.0'   

                                        reviews_list menu_item  \
0  [('Rated 4.0', 'RATED\n  A beautiful place to ...        []   
1  [('Rated 4.0', 'RATED\n  Had been here for din...        []   
2  [('Rated 3.0', "RATED\n  Ambience is not that ...        []   
3  [('Rated 4.0', "RATED\n  Great food and proper...        []   
4  [('Rated 4.0', 'RATED\n  Very good restaurant ...        []   

  listed_in(type) listed_in(city)  
0          Buffet    Banashankari  
1          Buffet    Banashankari  
2          Buffet    Banashankari  
3          Buffet    Banashankari  
4          Buffet    Banashankari

In [ ]:
#dataframe['col name']
df['name'] #series

0                                                    Jalsa
1                                           Spice Elephant
2                                          San Churro Cafe
3                                    Addhuri Udupi Bhojana
4                                            Grand Village
                               ...                        
23188                                   Izakaya Gastro Pub
23189          M Bar - Bengaluru Marriott Hotel Whitefield
23190                               Keys Cafe - Keys Hotel
23191                                              Bhagini
23192    Chime - Sheraton Grand Bengaluru Whitefield Ho...
Name: name, Length: 23193, dtype: object

In [ ]:
#np.array([1,2,3,4])
s1 = pd.Series([1,2,3,4],index=['a','b','c','d'])
s1

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
s1["b"]

np.int64(2)

In [ ]:
# Creating a DataFrame from a dictionary
data = {
    "Restaurant": ["R1", "R2", "R3"],
    "Votes": [120, 240, 150],
    "Rating": [4.1, 4.5, 3.9]
}

restaurant_df = pd.DataFrame(data)
restaurant_df

Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9

In [ ]:
restaurant_df['Votes']

0    120
1    240
2    150
Name: Votes, dtype: int64

In [ ]:
restaurant_df[['Votes',"Rating"]]

Votes  Rating
0    120     4.1
1    240     4.5
2    150     3.9

In [ ]:
#adding a column
df['rate']

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...  
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: object

In [ ]:
for i in df['rate']:
  print(i)
  print(i[:-2])
  break

4.1/5
4.1


In [ ]:
df['corrected_rating'] = [i[:-2] for i in df['rate']]

In [ ]:
df.head()

url  \
0  https://www.zomato.com/bangalore/jalsa-banasha...   
1  https://www.zomato.com/bangalore/spice-elephan...   
2  https://www.zomato.com/SanchurroBangalore?cont...   
3  https://www.zomato.com/bangalore/addhuri-udupi...   
4  https://www.zomato.com/bangalore/grand-village...   

                                             address                   name  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...                  Jalsa   
1  2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...         Spice Elephant   
2  1112, Next to KIMS Medical College, 17th Cross...        San Churro Cafe   
3  1st Floor, Annakuteera, 3rd Stage, Banashankar...  Addhuri Udupi Bhojana   
4  10, 3rd Floor, Lakshmi Associates, Gandhi Baza...          Grand Village   

  online_order book_table   rate  votes                             phone  \
0          Yes        Yes  4.1/5    775    080 42297555\r\n+91 9743772233   
1          Yes         No  4.1/5    787                      080 41714161   
2          Yes         No  3.8/5    918                    +91 9663487993   
3           No         No  3.7/5     88                    +91 9620009302   
4           No         No  3.8/5    166  +91 8026612447\r\n+91 9901210005   

       location            rest_type  \
0  Banashankari        Casual Dining   
1  Banashankari        Casual Dining   
2  Banashankari  Cafe, Casual Dining   
3  Banashankari          Quick Bites   
4  Basavanagudi        Casual Dining   

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Momos, Lunch Buffet, Chocolate Nirvana, Thai G...   
2  Churros, Cannelloni, Minestrone Soup, Hot Choc...   
3                                        Masala Dosa   
4                                Panipuri, Gol Gappe   

                         cuisines approx_cost(for two people)  \
0  North Indian, Mughlai, Chinese                     '800.0'   
1     Chinese, North Indian, Thai                     '800.0'   
2          Cafe, Mexican, Italian                     '800.0'   
3      South Indian, North Indian                     '300.0'   
4        North Indian, Rajasthani                     '600.0'   

                                        reviews_list menu_item  \
0  [('Rated 4.0', 'RATED\n  A beautiful place to ...        []   
1  [('Rated 4.0', 'RATED\n  Had been here for din...        []   
2  [('Rated 3.0', "RATED\n  Ambience is not that ...        []   
3  [('Rated 4.0', "RATED\n  Great food and proper...        []   
4  [('Rated 4.0', 'RATED\n  Very good restaurant ...        []   

  listed_in(type) listed_in(city) corrected_rating  
0          Buffet    Banashankari              4.1  
1          Buffet    Banashankari              4.1  
2          Buffet    Banashankari              3.8  
3          Buffet    Banashankari              3.7  
4          Buffet    Banashankari              3.8

In [ ]:
import numpy as np
arr = np.array([10,90,3,54])
np.sort(arr)

array([ 3, 10, 54, 90])

In [ ]:
np.sort(arr)[::-1]

array([ 3, 10, 54, 90])

In [ ]:
a2 = np.array([[10,12,3],[41,56,6]])
a2

array([[10, 12,  3],
       [41, 56,  6]])

In [ ]:
np.sort(a2,  )

array([[ 3, 10, 12],
       [ 6, 41, 56]])

In [ ]:
np.sort(a2,  )[::-1]

array([[ 6, 41, 56],
       [ 3, 10, 12]])