<a href="https://colab.research.google.com/github/krishnapranayangara/DataScience/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
even = np.arange(22,71,2)

In [ ]:
even

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [ ]:
odd = np.arange(21,72,2)

In [ ]:
odd

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [ ]:
mat =np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
print(mat[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
np.transpose(mat[::-1])

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [ ]:
import numpy as np
def rotate_img(mat):
      '''mat -> A 2d numpy array
       output -> A 2d numpy array is expected to be returned'''
      return np.transpose(mat[::-1])

In [ ]:
arr = [0, 1, 2, 3, 4, 5]

In [ ]:
arr[-1]

5

In [ ]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr.astype('float64')

array([10., 20., 30., 40., 50.])

In [ ]:
a = np.array([[6, 28], [8, 56], [7, 19]])

In [ ]:
np.transpose(a).reshape(1,6)

array([[ 6,  8,  7, 28, 56, 19]])

In [ ]:
marks_array = np.array([20, 35, 68, 82, 83, 70, 90])

In [ ]:
len(marks_array[marks_array>=80])

3

In [ ]:
len(marks_array[(60<=marks_array) & (marks_array<80)])

2

In [ ]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0


In [ ]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])

21


In [ ]:
matrix = np.array([[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]])

In [ ]:
matrix[:,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [ ]:
row_matrix = matrix[1:4]

In [ ]:
col_matrix = row_matrix[:,1:]

In [ ]:
col_matrix[::-1]

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

In [ ]:
matrix[::-1,1:]

array([[17, 18, 19],
       [13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7],
       [ 1,  2,  3]])

In [ ]:
matrix = np.array([[3, 3, 8, 2, 2, 1, 3, 9, 2, 3], [7, 9, 9, 7, 2, 2, 2, 7, 0, 5], [5, 1, 1, 9, 4, 7, 0, 4, 4, 8], [1, 3, 7, 2, 1, 1, 2, 0, 4, 3], [6, 4, 4, 4, 2, 5, 7, 3, 9, 6]])

In [ ]:
row_matrix = matrix[1:4]
col_matrix = row_matrix[:,-3:]
col_matrix[::-1]

array([[0, 4, 3],
       [4, 4, 8],
       [7, 0, 5]])

In [ ]:
matrix = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])

In [ ]:
np.transpose(np.transpose(matrix)[::-1])

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
result = []


In [ ]:
for col in matrix:
  result.append(col[::-1])

In [ ]:
result

[array([2, 1, 0]), array([5, 4, 3]), array([8, 7, 6])]

In [ ]:
a = np.array([[16, 5], [81, 6], [33, 1]])

In [ ]:
x=np.transpose(a).reshape(2,3)

In [ ]:
x

array([[16, 81, 33],
       [ 5,  6,  1]])

In [ ]:
x.flatten()

array([16, 81, 33,  5,  6,  1])

In [ ]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0

In [ ]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [ ]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [ ]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
np.hstack((arr, arr[:, [0]])).shape

(3, 4)

In [ ]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [ ]:
values = zip(birds,age)

In [ ]:
birds.sort()

In [ ]:
ranks = np.argsort(age)

In [ ]:
result = [birds[i] for i in ranks]

In [ ]:
result

['plovers',
 'plovers',
 'plovers',
 'plovers',
 'plovers',
 'Cranes',
 'spoonbills',
 'Cranes',
 'plovers',
 'spoonbills']

In [ ]:
array = np.array([[[ 0, 1, 2],
        [ 3, 4, 5],
        [ 6, 7, 8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [ ]:
array[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [ ]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
dim = (3,2)

In [ ]:
1 2
3 4
5 6

In [ ]:
np.pad(arr,dim,mode='edge')

In [ ]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

num_splits = 2

In [ ]:
data[:num_splits]

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
data[num_splits:]

array([[ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
np.concatenate((data[num_splits:], data[:num_splits]), axis=0)

array([[ 70,  80,  90],
       [100, 110, 120],
       [ 10,  20,  30],
       [ 40,  50,  60]])

In [ ]:
data = [[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]]
num_splits = 4

In [ ]:
data[:num_splits-1]

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [ ]:
data[num_splits-1:]

[[100, 110, 120]]

In [ ]:
new_data = []

In [ ]:
new_data.append(data[num_splits-1])
for i in range(0,num_splits-1):
  new_data.append(data[i])
  print(new_data)

[[100, 110, 120], [10, 20, 30]]
[[100, 110, 120], [10, 20, 30], [40, 50, 60]]
[[100, 110, 120], [10, 20, 30], [40, 50, 60], [70, 80, 90]]


In [ ]:
split_element = data[num_splits - 1]
elements_before_split = data[:num_splits - 1]
ans = [split_element] + elements_before_split
ans

[[100, 110, 120], [10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [ ]:
arr = np.array([[0, 1, 2, 3],
 [4, 5, 6, 7],
 [8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23]])

In [ ]:
arr[:,:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [ ]:
arr[:,2:3]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [ ]:
arr[:,3:]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])

In [ ]:
np.concatenate((arr[:,:2], arr[:,2:3], arr[:,3:]), axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
subarrays=[]
subarrays.append(arr[:,:2])
subarrays.append(arr[:,2:3])
subarrays.append(arr[:,3:])
subarrays

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19],
        [23]])]

In [ ]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
import pandas as pd

data = {
    'Country': ['Afghanistan', 'Australia', 'Brazil', 'China', 'France', 'India', 'United States'],
    'Year':  [1952, 1957, 1962, 1957, 1957, 1952, 1957],
    'Population':  [8425333.0, 9712569.0, 76039390.0, 637408000.0, 44310863.0, 372000000.0,  171984000.0],
    'Continent':  ['Asia', 'Oceania', 'Americas', 'Asia', 'Europe', 'Asia', 'Americas']
}

df = pd.DataFrame(data)

In [ ]:
import pandas as pd
def population_df(df):
   df_filtered = df[df['Population']>1000000]
   df_sorted = df.sort_values(by=['Year', 'Population'] )
   return df_sorted.reset_index(drop = True)

In [ ]:
population_df(df)

Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1          India  1952  372000000.0      Asia
2      Australia  1957    9712569.0   Oceania
3         France  1957   44310863.0    Europe
4  United States  1957  171984000.0  Americas
5          China  1957  637408000.0      Asia
6         Brazil  1962   76039390.0  Americas

In [ ]:
df[1:2]

Country  Year  Population Continent
1  Australia  1957   9712569.0   Oceania

In [ ]:
    name  amt
3  Rohan  150
2  Karie  400

In [ ]:
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic.T.drop_duplicates(keep="first")

0          1            2           3          4  \
survived               1          1            1           0          1   
pclass                 3          1            3           3          2   
sex               female     female       female        male     female   
age                 26.0       38.0         26.0         NaN       14.0   
sibsp                  0          1            0           0          1   
parch                  0          0            0           0          0   
fare               7.925    71.2833        7.925      8.4583    30.0708   
embarked               S          C            S           Q          C   
class              Third      First        Third       Third     Second   
adult_male         False      False        False        True      False   
embark_town  Southampton  Cherbourg  Southampton  Queenstown  Cherbourg   

                      5            6          7            8          9  
survived              0            0          1            1          1  
pclass                3            1          1            3          2  
sex                male         male     female       female     female  
age                 NaN         54.0       38.0         27.0       14.0  
sibsp                 0            0          1            0          1  
parch                 0            0          0            2          0  
fare             8.4583      51.8625    71.2833      11.1333    30.0708  
embarked              Q            S          C            S          C  
class             Third        First      First        Third     Second  
adult_male         True         True      False        False      False  
embark_town  Queenstown  Southampton  Cherbourg  Southampton  Cherbourg

In [ ]:
titanic.drop_duplicates(keep ="first")


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         1       3  female  26.0      0      0   7.9250        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
3         0       3    male   NaN      0      0   8.4583        Q   Third   
4         1       2  female  14.0      1      0  30.0708        C  Second   
6         0       1    male  54.0      0      0  51.8625        S   First   
8         1       3  female  27.0      0      2  11.1333        S   Third   

   adult_male  embark_town  pclass_1    price  gender  
0       False  Southampton         3   7.9250  female  
1       False    Cherbourg         1  71.2833  female  
3        True   Queenstown         3   8.4583    male  
4       False    Cherbourg         2  30.0708  female  
6        True  Southampton         1  51.8625    male  
8       False  Southampton         3  11.1333  female

In [ ]:
titanic.drop_duplicates(keep ="last")

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
2         1       3  female  26.0      0      0   7.9250        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         1       1  female  38.0      1      0  71.2833        C   First   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

   adult_male  embark_town  pclass_1    price  gender  
2       False  Southampton         3   7.9250  female  
5        True   Queenstown         3   8.4583    male  
6        True  Southampton         1  51.8625    male  
7       False    Cherbourg         1  71.2833  female  
8       False  Southampton         3  11.1333  female  
9       False    Cherbourg         2  30.0708  female

In [ ]:
df

Country  Year   Population Continent
0    Afghanistan  1952    8425333.0      Asia
1      Australia  1957    9712569.0   Oceania
2         Brazil  1962   76039390.0  Americas
3          China  1957  637408000.0      Asia
4         France  1957   44310863.0    Europe
5          India  1952  372000000.0      Asia
6  United States  1957  171984000.0  Americas

In [ ]:
df.iloc[:2,:2]

Country  Year
0  Afghanistan  1952
1    Australia  1957

In [ ]:

df.loc[:2,"Country":"Population"]

Country  Year  Population
0  Afghanistan  1952   8425333.0
1    Australia  1957   9712569.0
2       Brazil  1962  76039390.0

In [ ]:
sales = pd.read_csv("sales.csv")

In [ ]:
sales_sorted = sales.groupby('Invoice').apply(lambda x: x.sort_values(by='Quantity', ascending=False))


<ipython-input-57-2b6c5242e87a>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sales_sorted = sales.groupby('Invoice').apply(lambda x: x.sort_values(by='Quantity', ascending=False))


In [ ]:
sales_sorted

Invoice StockCode                         Description  \
Invoice                                                                 
489434  3        489434     22041        RECORD FRAME 7" SINGLE SIZE    
        6        489434     21871                 SAVE THE PLANET MUG   
        5        489434     22064          PINK DOUGHNUT TRINKET POT    
        4        489434     21232      STRAWBERRY CERAMIC TRINKET BOX   
        2        489434    79323W                 WHITE CHERRY LIGHTS   
...                 ...       ...                                 ...   
C538500 551609  C538500     82484   WOOD BLACK BOARD ANT WHITE FINISH   
C538530 552790  C538530     22630                DOLLY GIRL LUNCH BOX   
C538531 552828  C538531     21430  SET/3 RED GINGHAM ROSE STORAGE BOX   
C538536 552850  C538536     22834         HAND WARMER BABUSHKA DESIGN   
C538595 553454  C538595     82482   WOODEN PICTURE FRAME WHITE FINISH   

                Quantity          InvoiceDate  Price  Customer ID  \
Invoice                                                             
489434  3           48.0  2009-12-01 07:45:00   2.10      13085.0   
        6           24.0  2009-12-01 07:45:00   1.25      13085.0   
        5           24.0  2009-12-01 07:45:00   1.65      13085.0   
        4           24.0  2009-12-01 07:45:00   1.25      13085.0   
        2           12.0  2009-12-01 07:45:00   6.75      13085.0   
...                  ...                  ...    ...          ...   
C538500 551609      -2.0  2010-12-12 12:51:00   6.45      13715.0   
C538530 552790     -33.0  2010-12-13 10:26:00   1.95      14796.0   
C538531 552828      -2.0  2010-12-13 10:31:00   3.75      13715.0   
C538536 552850     -48.0  2010-12-13 10:40:00   0.85      15881.0   
C538595 553454      -2.0  2010-12-13 12:03:00   2.55      15555.0   

                       Country  amount  
Invoice                                 
489434  3       United Kingdom  100.80  
        6       United Kingdom   30.00  
        5       United Kingdom   39.60  
        4       United Kingdom   30.00  
        2       United Kingdom   81.00  
...                        ...     ...  
C538500 551609  United Kingdom  -12.90  
C538530 552790  United Kingdom  -64.35  
C538531 552828  United Kingdom   -7.50  
C538536 552850  United Kingdom  -40.80  
C538595 553454  United Kingdom   -5.10  

[553498 rows x 9 columns]

In [ ]:
high_sales = sales.groupby('Invoice')['Quantity'].sum()
high_sales.sort_values(ascending=False)

Invoice
524174     87167.0
518505     87167.0
497946     83774.0
501534     63974.0
495194     63302.0
            ...   
530348     -9000.0
504311     -9200.0
519017     -9600.0
C536757   -18720.0
C524235   -87167.0
Name: Quantity, Length: 28990, dtype: float64

In [ ]:
customers = sales.groupby('Invoice')['amount'].sum()
customers.sort_values(ascending=False)

Invoice
533027     49844.99
531516     45332.97
493819     44051.60
524181     33167.80
537659     31770.98
             ...   
C537651   -27082.66
C537630   -27082.66
A528059   -38925.87
A516228   -44031.79
A506401   -53594.36
Name: amount, Length: 28990, dtype: float64

In [ ]:
sales['amount'] = sales['Quantity'] * sales['Price']
customers = sales.groupby('Invoice')['amount'].sum()
customers.sort_values(ascending=False)

Invoice
533027     49844.99
531516     45332.97
493819     44051.60
524181     33167.80
537659     31770.98
             ...   
C537651   -27082.66
C537630   -27082.66
A528059   -38925.87
A516228   -44031.79
A506401   -53594.36
Name: amount, Length: 28990, dtype: float64

In [ ]:
highest_per_customer

Invoice StockCode                   Description  Quantity  \
27994   491725   TEST001       This is a test product.      10.0   
517879  537626     22492       MINI PAINT SET VINTAGE       36.0   
358167  524140     21213   PACK OF 72 SKULL CAKE CASES      24.0   
418678  529344     22740                  POLKADOT PEN      48.0   
499199  536012     22707             WRAP MONSTER FUN       25.0   
...        ...       ...                           ...       ...   
140853  502841    85230F         JASMINE VOTIVE CANDLE      12.0   
370345  525114     21498              RED SPOTS  WRAP       50.0   
93661   498149     22087      PAPER BUNTING WHITE LACE      80.0   
312065  519785     21829    DINOSAUR KEYRINGS ASSORTED      36.0   
199815  508581     84270  ASSTD DESIGN BUBBLE GUM RING      60.0   

                InvoiceDate  Price  Customer ID         Country  
27994   2009-12-14 08:34:00   4.50      12346.0  United Kingdom  
517879  2010-12-07 14:57:00   0.65      12347.0         Iceland  
358167  2010-09-27 14:59:00   0.55      12348.0         Finland  
418678  2010-10-28 08:23:00   0.85      12349.0           Italy  
499199  2010-11-29 15:23:00   0.42      12351.0     Unspecified  
...                     ...    ...          ...             ...  
140853  2010-03-28 13:21:00   0.29      18283.0  United Kingdom  
370345  2010-10-04 11:33:00   0.42      18284.0  United Kingdom  
93661   2010-02-17 10:24:00   2.55      18285.0  United Kingdom  
312065  2010-08-20 11:57:00   0.21      18286.0  United Kingdom  
199815  2010-05-17 11:55:00   0.21      18287.0  United Kingdom  

[4391 rows x 8 columns]

In [ ]:
max_row = sales.loc[sales['Quantity'].idxmax()]

# Extract the required details
invoice_number = max_row['Invoice']
customer_id = max_row['Customer ID']

In [ ]:
invoice_number

'497946'

In [ ]:
customer_id

np.float64(13902.0)

In [ ]:
import pandas as pd
df = pd.DataFrame({'City\tState': ["Kolkata\tWest Bengal", "Chennai\tTamil Nadu", "Hyderabad\tTelengana", "Bangalore\tKarnataka"]})

In [ ]:
df

City\tState
0  Kolkata\tWest Bengal
1   Chennai\tTamil Nadu
2  Hyderabad\tTelengana
3  Bangalore\tKarnataka

In [ ]:
df = df['City\tState'].str.split('\t', expand=True)

In [ ]:
df

0            1
0    Kolkata  West Bengal
1    Chennai   Tamil Nadu
2  Hyderabad    Telengana
3  Bangalore    Karnataka

In [ ]:
df.columns = ["City","State"]

In [ ]:
df

City        State
0    Kolkata  West Bengal
1    Chennai   Tamil Nadu
2  Hyderabad    Telengana
3  Bangalore    Karnataka

In [ ]:
for x in df.columns:
    if df[x].nunique()==1:
        df.drop(x, axis=1, inplace=True)

In [ ]:
df

City        State
0    Kolkata  West Bengal
1    Chennai   Tamil Nadu
2  Hyderabad    Telengana
3  Bangalore    Karnataka

In [ ]:
df["Extra"] = "Mumbai"

In [ ]:
df

City        State   Extra
0    Kolkata  West Bengal  Mumbai
1    Chennai   Tamil Nadu  Mumbai
2  Hyderabad    Telengana  Mumbai
3  Bangalore    Karnataka  Mumbai

In [ ]:
df = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"])

In [ ]:
df

emp_id   name dept
0       1    Ram   IT
1       2  Shyam  Ops

In [ ]:
import pandas as pd
df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})

In [ ]:
df = pd.DataFrame({'name':["Mark","Ram","Dev","Clark"], "profession":['dev','mle','mle','sde'],"gender":['female','male','female','male'], "age":[21,20,30,25],"review":['need improvement','Can be improved','Scope of improvement','Can be improved'],"rating":[10,5,7,10]})


In [ ]:
df = ["a","b","a","c"]

In [ ]:
df["gender"].nunique()

2

In [ ]:
df_new = df[df["gender"] == "male"]

In [ ]:
df_new

index   name profession  gender  age                review  rating
0      2    Dev        mle  female   30  Scope of improvement       7
1      3  Clark        sde    male   25       Can be improved      10

In [ ]:
df_new = df_new[(df_new["age"]>=23) & (df_new["age"]<=30)].reset_index()

df_new['name']

0      Dev
1    Clark
Name: name, dtype: object

In [ ]:
data = [['d', 20], ['e', 21], ['f', 22]]

In [ ]:
df = {'name': ['a', 'b', 'c'], 'age': [12, 15, 18]}

In [ ]:
new_names, new_ages = zip(*data)

df['name'].extend(new_names)
df['age'].extend(new_ages)

In [ ]:
df

{'name': ['a', 'b', 'c', 'd', 'e', 'f'], 'age': [12, 15, 18, 20, 21, 22]}

In [ ]:
import pandas as pd
df = pd.read_csv("sales.csv")

In [ ]:
df.head()

Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12   
1  489434    79323P                   PINK CHERRY LIGHTS        12   
2  489434    79323W                  WHITE CHERRY LIGHTS        12   
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48   
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24   

           InvoiceDate  Price  Customer ID         Country  
0  2009-12-01 07:45:00   6.95      13085.0  United Kingdom  
1  2009-12-01 07:45:00   6.75      13085.0  United Kingdom  
2  2009-12-01 07:45:00   6.75      13085.0  United Kingdom  
3  2009-12-01 07:45:00   2.10      13085.0  United Kingdom  
4  2009-12-01 07:45:00   1.25      13085.0  United Kingdom

In [ ]:
highest = pd.DataFrame(df.groupby("Description")["Quantity"].sum())

In [ ]:
highest.sort_values(by="Quantity",ascending=False)

Quantity
Description                                 
WORLD WAR 2 GLIDERS ASSTD DESIGNS     108545
WHITE HANGING HEART T-LIGHT HOLDER     93050
ASSORTED COLOUR BIRD ORNAMENT          81306
JUMBO BAG RED RETROSPOT                78090
BROCADE RING PURSE                     70700
...                                      ...
Unsaleable, destroyed.                -15644
missing                               -16467
printing smudges/thrown away          -19200
given away                            -20000
?                                     -26757

[5698 rows x 1 columns]

In [ ]:
df[df["StockCode"]=="85123A"]

Invoice StockCode                         Description  Quantity  \
102      489442    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
147      489446    85123A  WHITE HANGING HEART T-LIGHT HOLDER        32   
271      489465    85123A  WHITE HANGING HEART T-LIGHT HOLDER        64   
284      489467    85123A                         21733 mixed      -192   
366      489517    85123A  WHITE HANGING HEART T-LIGHT HOLDER         1   
...         ...       ...                                 ...       ...   
1064803  581439    85123A  CREAM HANGING HEART T-LIGHT HOLDER         1   
1065440  581452    85123A  WHITE HANGING HEART T-LIGHT HOLDER        32   
1065678  581472    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
1066298  581492    85123A  CREAM HANGING HEART T-LIGHT HOLDER         3   
1067100  581538    85123A  CREAM HANGING HEART T-LIGHT HOLDER         1   

                 InvoiceDate  Price  Customer ID         Country  
102      2009-12-01 09:46:00   2.95      13635.0  United Kingdom  
147      2009-12-01 10:06:00   2.55      13758.0  United Kingdom  
271      2009-12-01 10:52:00   2.55      13767.0  United Kingdom  
284      2009-12-01 10:53:00   0.00          NaN  United Kingdom  
366      2009-12-01 11:34:00   2.95      16329.0  United Kingdom  
...                      ...    ...          ...             ...  
1064803  2011-12-08 16:30:00   5.79          NaN  United Kingdom  
1065440  2011-12-08 18:03:00   2.55      17675.0  United Kingdom  
1065678  2011-12-08 19:55:00   2.95      15796.0  United Kingdom  
1066298  2011-12-09 10:03:00   5.79          NaN  United Kingdom  
1067100  2011-12-09 11:34:00   2.95      14446.0  United Kingdom  

[5829 rows x 8 columns]

In [ ]:
df[df["Customer ID"] == 16446]

Invoice StockCode                  Description  Quantity  \
371780   C525275   TEST001      This is a test product.        -2   
719815    553573     22980       PANTRY SCRUBBING BRUSH         1   
719816    553573     22982          PANTRY PASTRY BRUSH         1   
1065882   581483     23843  PAPER CRAFT , LITTLE BIRDIE     80995   
1065883  C581484     23843  PAPER CRAFT , LITTLE BIRDIE    -80995   

                 InvoiceDate  Price  Customer ID         Country  
371780   2010-10-04 16:38:00   4.50      16446.0  United Kingdom  
719815   2011-05-18 09:52:00   1.65      16446.0  United Kingdom  
719816   2011-05-18 09:52:00   1.25      16446.0  United Kingdom  
1065882  2011-12-09 09:15:00   2.08      16446.0  United Kingdom  
1065883  2011-12-09 09:27:00   2.08      16446.0  United Kingdom

In [ ]:
df["Amount"] = df["Quantity"] * df["Price"]

In [ ]:
df.sort_values(by = "Quantity", ascending = False)

Invoice StockCode                         Description  Quantity  \
1065882   581483     23843         PAPER CRAFT , LITTLE BIRDIE     80995   
587080    541431     23166      MEDIUM CERAMIC TOP STORAGE JAR     74215   
90857     497946     37410  BLACK AND WHITE PAISLEY FLOWER MUG     19152   
127168    501534     21091         SET/6 WOODLAND PAPER PLATES     12960   
127166    501534     21099         SET/6 STRAWBERRY PAPER CUPS     12960   
...          ...       ...                                 ...       ...   
303996    519017     22759                                 NaN     -9600   
750990    556690     23005        printing smudges/thrown away     -9600   
750991    556691     23005        printing smudges/thrown away     -9600   
587085   C541433     23166      MEDIUM CERAMIC TOP STORAGE JAR    -74215   
1065883  C581484     23843         PAPER CRAFT , LITTLE BIRDIE    -80995   

                 InvoiceDate  Price  Customer ID         Country  
1065882  2011-12-09 09:15:00   2.08      16446.0  United Kingdom  
587080   2011-01-18 10:01:00   1.04      12346.0  United Kingdom  
90857    2010-02-15 11:57:00   0.10      13902.0         Denmark  
127168   2010-03-17 13:09:00   0.10      13902.0         Denmark  
127166   2010-03-17 13:09:00   0.10      13902.0         Denmark  
...                      ...    ...          ...             ...  
303996   2010-08-13 09:14:00   0.00          NaN  United Kingdom  
750990   2011-06-14 10:37:00   0.00          NaN  United Kingdom  
750991   2011-06-14 10:37:00   0.00          NaN  United Kingdom  
587085   2011-01-18 10:17:00   1.04      12346.0  United Kingdom  
1065883  2011-12-09 09:27:00   2.08      16446.0  United Kingdom  

[1067371 rows x 8 columns]

In [ ]:
import pandas as pd

data = {
    'ord_no': [70001, 70009, 70002, 70004, 70007, 70005, 70008, 70010, 70003, 70012, 70011, 70013],
    'purch_amt': [150.50, 270.65, 65.26, 110.50, 948.50, 2400.60, 5760.00, 1983.43, 2480.40, 250.45, 75.29, 3045.60],
    'ord_date': ['2012-10-05', '2012-09-10', '2012-10-05', '2012-08-17', '2012-09-10', '2012-07-27', '2012-09-10', '2012-10-10', '2012-10-10', '2012-06-27', '2012-08-17', '2012-04-25'],
    'customer_id': [3005, 3001, 3002, 3009, 3005, 3007, 3002, 3004, 3009, 3008, 3003, 3002],
    'salesman_id': [5002, 5005, 5001, 5003, 5002, 5001, 5001, 5006, 5003, 5002, 5007, 5001]
}

df = pd.DataFrame(data)

In [ ]:
df_ne = df.groupby(by = ["salesman_id","customer_id"])["ord_date"].count()

In [ ]:
df_new = pd.DataFrame(df_ne)

In [ ]:
df_new.reset_index(inplace=True)

In [ ]:
df_new.groupby(by=["salesman_id"])

In [ ]:
df_new

salesman_id  customer_id  ord_date
0         5001         3002         3
1         5001         3007         1
2         5002         3005         2
3         5002         3008         1
4         5003         3009         2
5         5005         3001         1
6         5006         3004         1
7         5007         3003         1

In [ ]:
import pandas as pd

data = {
    'cust_id': [101, 102, 103, 104],
    'name': ['rick', 'morty', 'pickle', 'jerry']
}

customer = pd.DataFrame(data)

In [ ]:
import pandas as pd

data = {
    'order_id': ['OR1', 'OR3', 'OR23', 'OR42'],
    'cust_id': [102, 105, 101, 102],
    'amount': [1200, 650, 120, 989]
}

orders = pd.DataFrame(data)

In [ ]:
merged_df = customer.merge(orders,how="left")

In [ ]:
merged_df

cust_id    name order_id  amount
0      101    rick     OR23   120.0
1      102   morty      OR1  1200.0
2      102   morty     OR42   989.0
3      103  pickle      NaN     NaN
4      104   jerry      NaN     NaN

In [ ]:
total = merged_df[merged_df["name"]=="morty"]["amount"].sum()

In [ ]:
total

np.float64(2189.0)

In [ ]:
import pandas as pd

data = {
    'name': ['Elon', 'Jeff', 'Bill', 'Falguni'],
    'gender': ['M', 'F', 'M', 'F'],
    'income': [53000.0, 28000.0, 25000.0, 44000.0]
}

df = pd.DataFrame(data)

In [ ]:
series = df.groupby("gender")["income"].agg("mean")

In [ ]:
series

gender
F    36000.0
M    39000.0
Name: income, dtype: float64

In [ ]:
df

name gender   income
0     Elon      M  53000.0
1     Jeff      F  28000.0
2     Bill      M  25000.0
3  Falguni      F  44000.0

In [ ]:
df = pd.DataFrame([['2019-03-23 20:21:09', '2019-03-23 20:27:24', 1, 1.6], ['2019-03-04 16:11:55', '2019-03-04 16:19:00', 1, 0.79], ['2019-03-27 17:53:01', '2019-03-27 18:00:25', 1, 1.37], ['2019-03-10 01:23:59', '2019-03-10 01:49:51', 1, 7.70], ['2019-03-30 13:27:42', '2019-03-30 13:37:14', 3, 2.16]], columns = ['pickup', 'dropoff', 'passengers', 'distance'])

In [ ]:
df

pickup              dropoff  passengers  distance
0  2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60
1  2019-03-04 16:11:55  2019-03-04 16:19:00           1      0.79
2  2019-03-27 17:53:01  2019-03-27 18:00:25           1      1.37
3  2019-03-10 01:23:59  2019-03-10 01:49:51           1      7.70
4  2019-03-30 13:27:42  2019-03-30 13:37:14           3      2.16

In [ ]:
df["pickup"] =df["pickup"].astype(str)
df[["date","time"]] = df["pickup"].str.split(' ', expand=True)
df['time_of_day'] = pd.to_datetime(df['time']).dt.hour
bins = [-1, 6, 12, 18, 24]
labels = ['morning', 'day', 'afternoon', 'night']

df['time_of_day'] = pd.cut(df['time_of_day'], bins=bins, labels=labels, right=False)
pickups = df['time_of_day'].value_counts().sort_values(ascending=False)
pickups

time_of_day
afternoon    3
morning      1
night        1
day          0
Name: count, dtype: int64

In [ ]:
df.sort_values(by ="pickup")["time_of_day"].value_counts()

time_of_day
afternoon    3
morning      1
night        1
day          0
Name: count, dtype: int64

In [ ]:
df["pickup"] = df["pickup"].astype(str)
df[["date", "time"]] = df["pickup"].str.split(' ', expand=True)
df['time_of_day_hour'] = pd.to_datetime(df['time']).dt.hour

bins = [-1, 6, 12, 18, 24]
labels = ['morning', 'day', 'afternoon', 'night']

df['time_of_day'] = pd.cut(df['time_of_day_hour'], bins=bins, labels=labels, right=False)

pickups_series = df['time_of_day'].value_counts().sort_values(ascending=False)

pickups_series.index.name = 'time_of_day'
pickups_series.name = 'pickup'

print(pickups_series)

time_of_day
afternoon    3
morning      1
night        1
day          0
Name: pickup, dtype: int64


<ipython-input-143-2566c3012a66>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['time_of_day_hour'] = pd.to_datetime(df['time']).dt.hour


In [ ]:
reg_id = ["56","92"," 29"," 93"," 55 ","32"]

reg_dates = ["2021-01-01","2021-02-12", "2021-04-16", "2021-01-22", "2021-01-15", "2021-02-26"]

In [ ]:
res_df = pd.DataFrame(zip(reg_id, reg_dates), columns=["RID", "RDate"])

In [ ]:
res_df

RID       RDate
0    56  2021-01-01
1    92  2021-02-12
2    29  2021-04-16
3    93  2021-01-22
4   55   2021-01-15
5    32  2021-02-26

In [ ]:
def solve(reg_id, reg_dates):
    res_df = pd.DataFrame(zip(reg_id, reg_dates), columns=["RID", "RDate"])
    """
    input:
    reg_id -> id of the input dataframe
    reg_dates -> dates of the input dataframe
    res_df -> the input dataframe

    output:
    return the resultant dataframe after performing the required operation
    """
    # YOUR CODE GOES HERE
    res_df["RDate"] = res_df["RDate"].astype(str)
    res_df[["RYear","RMonth","RDay"]] = res_df["RDate"].str.split("-",expand=True)
    res_df["RMonth"] = res_df["RMonth"].astype(int)
    res_df["RYear"] = res_df["RYear"].astype(int)
    res_df["RDay"] = res_df["RDay"].astype(int)

    return res_df

In [ ]:
solve(reg_id, reg_dates)

RID       RDate  RYear  RMonth  RDay
0    56  2021-01-01   2021       1     1
1    92  2021-02-12   2021       2    12
2    29  2021-04-16   2021       4    16
3    93  2021-01-22   2021       1    22
4   55   2021-01-15   2021       1    15
5    32  2021-02-26   2021       2    26

In [ ]:
import pandas as pd

data = {
    'name': ['Jim', 'Clarke', 'Kent', 'Mark'],
    'username': ['itsjimhere', 'clark002', 'itskentment', 'markyoumustknow'],
    'userid': [20, 10, 86, 21]
}

df = pd.DataFrame(data)

In [ ]:
def check(name,username):
    return name.lower() in username



In [ ]:
df[~(df.apply(lambda x:check(x['name'],x['username']), axis=1))]['userid']

1    10
Name: userid, dtype: int64

In [ ]:
data = {'name':["Ram","Shyam","Mukesh","Suresh"],'age':[10,18,60,50]}
df = pd.DataFrame(data)

In [ ]:
def age(age):
    if age<18:
      return "Kid"
    elif age>=18 and age<=50:
      return "adult"
    else:
      return "senior"

In [ ]:
df["age"] = df.apply(lambda x:age(x['age']),axis=1)

In [ ]:
df

name     age
0     Ram     Kid
1   Shyam   adult
2  Mukesh  senior
3  Suresh   adult

In [ ]:
def replace_ages(a):
    '''a is a dataframe with columns ['name', 'age']
       Output A dataframe with same columns but with changed records as per required is expected to be returned'''

    # YOUR CODE GOES HERE
    def age(age):
      if age<18:
         return "Kid"
      elif age>=18 and age<=50:
         return "adult"
      else:
         return "senior"

    df["age"] = df.apply(lambda x:age(x['age']),axis=1)
    return df

In [8]:
import pandas as pd
import numpy as np
sales_data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'Region': ['East', 'West', 'East', 'West'],
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [100, 200, np.nan, 250]
}

df = pd.DataFrame(sales_data)

In [ ]:
df.fillna(0)

Date Region Product  Sales
0  2024-01-01   East       A  100.0
1  2024-01-01   West       B  200.0
2  2024-01-02   East       A    0.0
3  2024-01-02   West       B  250.0

In [ ]:
result = pd.DataFrame(df.groupby(by=["Region"])["Sales"].sum())
result

Sales
Region       
East    100.0
West    450.0

In [9]:
data = pd.DataFrame(np.transpose(df))

In [10]:
data

0           1           2           3
Date     2024-01-01  2024-01-01  2024-01-02  2024-01-02
Region         East        West        East        West
Product           A           B           A           B
Sales         100.0       200.0         NaN       250.0

In [118]:

df = pd.DataFrame([['Canada', 70.6, 78.3, 80.2, 82.3, 81.4, 80.3], ['France', 71.8, 74.7, 79.32, 77.2, 80.0, 81.2], ['Germany', 74.8, 74.7, 77.32, 77.2, 80.0, 81.2], ['Japan', 74.9, 74.7, 77.32, 77.8, 82.0, 81.2], ['Korea', 74.1, 74.7, 77.32, 77.2, 80.0, 83.2]], columns = ['Country', 2000, 2001, 2002, 2003, 2004, 2005])

print(df)

   Country  2000  2001   2002  2003  2004  2005
0   Canada  70.6  78.3  80.20  82.3  81.4  80.3
1   France  71.8  74.7  79.32  77.2  80.0  81.2
2  Germany  74.8  74.7  77.32  77.2  80.0  81.2
3    Japan  74.9  74.7  77.32  77.8  82.0  81.2
4    Korea  74.1  74.7  77.32  77.2  80.0  83.2


In [106]:
df_t = df.transpose()

In [107]:
#change index country to Year
df_t.reset_index(inplace=True)

In [108]:
df_t.columns = ["Year","Canada","France","Germany","Great Britain","Japan"]

In [109]:
df_t.drop(0,axis=0,inplace=True)

In [110]:
df_t

Year Canada France Germany Great Britain  Japan
1  2000   70.6   71.8    74.8          74.9   74.1
2  2001   78.3   74.7    74.7          74.7   74.7
3  2002   80.2  79.32   77.32         77.32  77.32
4  2003   82.3   77.2    77.2          77.8   77.2
5  2004   81.4   80.0    80.0          82.0   80.0
6  2005   80.3   81.2    81.2          81.2   83.2

In [102]:
df_t["Average"] = df_t.drop("Year",axis=1).apply(lambda x:x.mean(),axis=1)

In [104]:
df_t.sort_values(by="Average",ascending=False)

Year Canada France Germany Great Britain Japan  Average
9  2008   80.7   81.4    80.2          79.8  82.7    80.96
8  2007   80.5   81.2    80.1          79.7  82.6    80.82
7  2006   80.4   81.0    79.8          79.5  82.4    80.62
6  2005   80.0   80.4    79.4          79.2  82.0    80.20
5  2004   79.9   80.3    79.2          79.0  82.1    80.10
4  2003   79.6   79.3    78.6          78.4  81.8    79.54
3  2002   79.5   79.4    78.5          78.3  81.8    79.50
2  2001   79.3   79.3    78.5          78.2  81.5    79.36
1  2000   79.1   79.2    78.2          77.9  81.2    79.12

In [113]:
df

Country  2000  2001   2002  2003  2004  2005    Average
0   Canada  70.6  78.3  80.20  82.3  81.4  80.3  78.850000
1   France  71.8  74.7  79.32  77.2  80.0  81.2  77.370000
2  Germany  74.8  74.7  77.32  77.2  80.0  81.2  77.536667
3    Japan  74.9  74.7  77.32  77.8  82.0  81.2  77.986667
4    Korea  74.1  74.7  77.32  77.2  80.0  83.2  77.753333

In [132]:
df_avg_year = df.drop("Country", axis=1).mean(axis=0)
df_avg_year.index.name = "Year"
df_avg_year.name = "Life_Expectancy"

In [131]:
df_avg_year

Year
2000    73.240
2001    75.420
2002    78.296
2003    78.340
2004    80.680
2005    81.420
Name: Average, dtype: float64

In [133]:
    df_avg_year = df.drop("Country", axis=1).mean(axis=0)
    df_avg_year.index.name = "Year"
    df_avg_year.name = "Life_Expectancy"
    df_avg_year = pd.DataFrame(df_avg_year)
    df_avg_year = df_avg_year.sort_values("Life_Expectancy")

In [136]:
df_avg_year.sort_values("Life_Expectancy",ascending=False)

Life_Expectancy
Year                 
2005           81.420
2004           80.680
2003           78.340
2002           78.296
2001           75.420
2000           73.240

In [155]:
import pandas as pd


data_df1 = {
    'A': [1, 2, 3, 4],
    'B': [11, 22, 33, 44],
    'C': [111, 222, 333, 444]
}
index_df1 = ['first', 'second', 'third', 'fourth']
df1 = pd.DataFrame(data_df1, index=index_df1)


data_df2 = {
    'D': ['a', 'b', 'c', 'd'],
    'E': ['aa', 'bb', 'cc', 'dd'],
    'F': ['aaa', 'bbb', 'ccc', 'ddd']
}
index_df2 = ['fourth', 'fifth', 'sixth', 'seventh']
df2 = pd.DataFrame(data_df2, index=index_df2)


In [156]:
df3=pd.concat([df1,df2])

In [157]:
df3

A     B      C    D    E    F
first    1.0  11.0  111.0  NaN  NaN  NaN
second   2.0  22.0  222.0  NaN  NaN  NaN
third    3.0  33.0  333.0  NaN  NaN  NaN
fourth   4.0  44.0  444.0  NaN  NaN  NaN
fourth   NaN   NaN    NaN    a   aa  aaa
fifth    NaN   NaN    NaN    b   bb  bbb
sixth    NaN   NaN    NaN    c   cc  ccc
seventh  NaN   NaN    NaN    d   dd  ddd

In [158]:
#Block a
df4=df3.drop(["fourth"])


In [159]:
df4

A     B      C    D    E    F
first    1.0  11.0  111.0  NaN  NaN  NaN
second   2.0  22.0  222.0  NaN  NaN  NaN
third    3.0  33.0  333.0  NaN  NaN  NaN
fifth    NaN   NaN    NaN    b   bb  bbb
sixth    NaN   NaN    NaN    c   cc  ccc
seventh  NaN   NaN    NaN    d   dd  ddd

In [ ]:
df3=pd.concat([df1,df2])




#Block c
df3.loc['fourth','A']*2

In [ ]:
#Block b
df4 = df3.reset_index().drop_duplicates(subset='index', keep='last')
df4 = df4.set_index('index').sort_index()

In [160]:
df4 = df3.reset_index().drop_duplicates(subset='index', keep='last')


In [161]:
df4

index    A     B      C    D    E    F
0    first  1.0  11.0  111.0  NaN  NaN  NaN
1   second  2.0  22.0  222.0  NaN  NaN  NaN
2    third  3.0  33.0  333.0  NaN  NaN  NaN
4   fourth  NaN   NaN    NaN    a   aa  aaa
5    fifth  NaN   NaN    NaN    b   bb  bbb
6    sixth  NaN   NaN    NaN    c   cc  ccc
7  seventh  NaN   NaN    NaN    d   dd  ddd

In [162]:
df4 = df4.set_index('index').sort_index()

In [163]:
df4

A     B      C    D    E    F
index                                   
fifth    NaN   NaN    NaN    b   bb  bbb
first    1.0  11.0  111.0  NaN  NaN  NaN
fourth   NaN   NaN    NaN    a   aa  aaa
second   2.0  22.0  222.0  NaN  NaN  NaN
seventh  NaN   NaN    NaN    d   dd  ddd
sixth    NaN   NaN    NaN    c   cc  ccc
third    3.0  33.0  333.0  NaN  NaN  NaN

In [164]:
import pandas as pd

data = {
    'roll_no': [1, 2, 1, 3, 1, 3, 3, 3, 2, 2, 1, 2],
    'subject': ['NN', 'DL', 'ML', 'Prob', 'DL', 'ML', 'DL', 'NN', 'NN', 'Prob', 'Prob', 'ML'],
    'marks': [97, 63, 63, 71, 64, 90, 66, 46, 74, 62, 94, 67]
}

df = pd.DataFrame(data)

In [177]:
df_marks = df.groupby(by=["subject"])["marks"].max()
df_marks = pd.DataFrame(df_marks)
df_marks.reset_index(inplace=True)

In [178]:
df_marks.merge(df,how="left")

subject  marks  roll_no
0      DL     66        3
1      ML     90        3
2      NN     97        1
3    Prob     94        1

In [179]:
max_marks = pd.DataFrame(df.groupby(by=["subject"])["marks"].max())